.TH VALTHON 1
.SH NAME
vln2py \- Translate valthon files to python
.SH SYNOPSIS
.B vln2py
[\fIFLAGS\fR]
.IR scriptfile
.SH DESCRIPTION
.B vln2py
is an alias for 'valthon -c'. For more information, look up the manual for valthon(1).
.SH SEE ALSO
valthon(1)
.SH AUTHOR
Harshal Laheri 2025
.SH LICENSE
This program is licensed under the MIT license. See [1] for details. TL;DR: Do whatever you want as long as you include the original copyright and license notice.
.TP
[1]
